// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ws.Core.Data;

#nullable disable

namespace Ws.Core.Data.Migrations
{
    [DbContext(typeof(WsDbContext))]
    [Migration("20260926174026_SalonCountryAndCover")]
    partial class SalonCountryAndCover
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Ws.Core.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstagramHandle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Styles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Ws.Core.Domain.ArtistService", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PriceFrom")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceTo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtistId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ArtistServices");
                });

            modelBuilder.Entity("Ws.Core.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BlockedUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclineOrCancelReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsPrivateRoom")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Reminder24hSentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Reminder2hSentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WithGuardian")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ArtistId", "StartUtc");

                    b.HasIndex("SalonId", "StartUtc");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Ws.Core.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalonId", "Phone");

                    b.HasIndex("SalonId", "TelegramUserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Ws.Core.Domain.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMessageAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsHuman")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SalonId", "Channel", "ExternalId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Ws.Core.Domain.ConversationMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("Ws.Core.Domain.PortfolioImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("PortfolioImages");
                });

            modelBuilder.Entity("Ws.Core.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Workstations")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Ws.Core.Domain.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBookingDaysAhead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAgeSolo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAgeWithGuardian")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinBookingLeadMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotStepMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("Ws.Core.Domain.SalonHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Close")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Open")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("SalonHours");
                });

            modelBuilder.Entity("Ws.Core.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdultsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BookableOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsPrivateRoom")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PriceFrom")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceTo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Ws.Core.Domain.TimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "StartUtc");

                    b.ToTable("TimeOff");
                });

            modelBuilder.Entity("Ws.Core.Domain.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("Ws.Core.Domain.Artist", b =>
                {
                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "Bio", b1 =>
                        {
                            b1.Property<int>("ArtistId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("ArtistId");

                            b1.ToTable("Artists");

                            b1
                                .ToJson("Bio")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");
                        });

                    b.Navigation("Bio")
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.ArtistService", b =>
                {
                    b.HasOne("Ws.Core.Domain.Artist", "Artist")
                        .WithMany("Services")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ws.Core.Domain.Service", "Service")
                        .WithMany("Artists")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Ws.Core.Domain.Booking", b =>
                {
                    b.HasOne("Ws.Core.Domain.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ws.Core.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ws.Core.Domain.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ws.Core.Domain.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ws.Core.Domain.TattooDetails", "Tattoo", b1 =>
                        {
                            b1.Property<int>("BookingId");

                            b1.Property<bool?>("ColorWork");

                            b1.Property<string>("Idea");

                            b1.Property<string>("Placement");

                            b1.PrimitiveCollection<string>("ReferenceImageUrls")
                                .IsRequired();

                            b1.Property<string>("Size");

                            b1.Property<string>("Style");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1
                                .ToJson("Tattoo")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("Artist");

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Tattoo");
                });

            modelBuilder.Entity("Ws.Core.Domain.Client", b =>
                {
                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.Conversation", b =>
                {
                    b.HasOne("Ws.Core.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.ConversationMessage", b =>
                {
                    b.HasOne("Ws.Core.Domain.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.PortfolioImage", b =>
                {
                    b.HasOne("Ws.Core.Domain.Artist", null)
                        .WithMany("Portfolio")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "Caption", b1 =>
                        {
                            b1.Property<int>("PortfolioImageId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("PortfolioImageId");

                            b1.ToTable("PortfolioImages");

                            b1
                                .ToJson("Caption")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("PortfolioImageId");
                        });

                    b.Navigation("Caption")
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.Room", b =>
                {
                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany("Rooms")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.Salon", b =>
                {
                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "About", b1 =>
                        {
                            b1.Property<int>("SalonId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("SalonId");

                            b1.ToTable("Salons");

                            b1
                                .ToJson("About")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SalonId");
                        });

                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "Address", b1 =>
                        {
                            b1.Property<int>("SalonId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("SalonId");

                            b1.ToTable("Salons");

                            b1
                                .ToJson("Address")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SalonId");
                        });

                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "Policies", b1 =>
                        {
                            b1.Property<int>("SalonId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("SalonId");

                            b1.ToTable("Salons");

                            b1
                                .ToJson("Policies")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("SalonId");
                        });

                    b.Navigation("About")
                        .IsRequired();

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Policies")
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.SalonHours", b =>
                {
                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany("OpeningHours")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.Service", b =>
                {
                    b.HasOne("Ws.Core.Domain.Salon", null)
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<int>("ServiceId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1
                                .ToJson("Description")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.OwnsOne("Ws.Core.Domain.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("ServiceId");

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.Property<string>("Ru")
                                .IsRequired();

                            b1.HasKey("ServiceId");

                            b1.ToTable("Services");

                            b1
                                .ToJson("Name")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ServiceId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.TimeOff", b =>
                {
                    b.HasOne("Ws.Core.Domain.Artist", null)
                        .WithMany("TimeOff")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.WorkingHours", b =>
                {
                    b.HasOne("Ws.Core.Domain.Artist", null)
                        .WithMany("WorkingHours")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ws.Core.Domain.Artist", b =>
                {
                    b.Navigation("Portfolio");

                    b.Navigation("Services");

                    b.Navigation("TimeOff");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("Ws.Core.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ws.Core.Domain.Salon", b =>
                {
                    b.Navigation("OpeningHours");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Ws.Core.Domain.Service", b =>
                {
                    b.Navigation("Artists");
                });
#pragma warning restore 612, 618
        }
    }
}
