using Anthropic.Exceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Ws.Core.Data;
using Ws.Core.Domain;
using Ws.Core.Receptionist;

namespace Ws.Api.Controllers;

/// <summary>Website chat widget: a thin channel adapter over the Receptionist.</summary>
[Route("api/chat")]
public sealed class ChatController(
    WsDbContext db, IServiceProvider services, IOptions<WsOptions> options, ILogger<ChatController> log) : ApiControllerBase
{
    [HttpPost]
    [EnableRateLimiting(RateLimits.Chat)]
    public async Task<ActionResult<ChatResponse>> Send(ChatRequest req, CancellationToken ct)
    {
        if (!ValidSession(req.SessionId) || string.IsNullOrWhiteSpace(req.Message)) return Invalid("message", "Message and session are required.");

        // No Claude API key configured: the widget shows a "call us" message instead.
        var receptionist = services.GetService<Receptionist>();
        if (receptionist == null) return Problem(statusCode: 503, title: "Chat is not configured", type: "ChatUnavailable");

        try
        {
            var reply = await receptionist.ReplyAsync(options.Value.SalonId, Channel.WebChat, req.SessionId, req.Message, req.Language, ct);
            return new ChatResponse(reply.Text, reply.NeedsHuman);
        }
        catch (AnthropicApiException ex)
        {
            log.LogError(ex, "Claude API error in web chat");
            return Problem(statusCode: 503, title: "Chat is temporarily unavailable", type: "ChatUnavailable");
        }
    }

    /// <summary>Earlier messages of this browser's chat, for when the widget reopens.</summary>
    [HttpGet("{sessionId}")]
    public async Task<ActionResult<IEnumerable<ChatMessageDto>>> History(string sessionId, CancellationToken ct)
    {
        if (!ValidSession(sessionId)) return NotFound();
        var salonId = options.Value.SalonId;

        var messages = await db.ConversationMessages.AsNoTracking()
            .Where(m => db.Conversations.Any(c => c.Id == m.ConversationId && c.SalonId == salonId
                                                  && c.Channel == Channel.WebChat && c.ExternalId == sessionId))
            .Where(m => (m.Role == MessageRole.User || m.Role == MessageRole.Assistant || m.Role == MessageRole.Staff) && m.Text != "")
            .OrderBy(m => m.Id)
            .Select(m => new ChatMessageDto(m.Role == MessageRole.User ? "user" : "assistant", m.Text, m.CreatedAtUtc))
            .ToListAsync(ct);
        return messages;
    }

    /// <summary>Session ids are random UUIDs generated by the widget; anything else is rejected.</summary>
    private static bool ValidSession(string? id) => Guid.TryParse(id, out _);
}

public sealed record ChatRequest(string SessionId, string Message, string? Language);
public sealed record ChatResponse(string Reply, bool NeedsHuman);
public sealed record ChatMessageDto(string Role, string Text, DateTime At);
