using Anthropic.Exceptions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Ws.Core.Data;
using Ws.Core.Domain;
using Ws.Core.Receptionist;

namespace Ws.Api.Endpoints;

/// <summary>Website chat widget: a thin channel adapter over the Receptionist.</summary>
public static class ChatEndpoints
{
    public const string RateLimitPolicy = "chat";

    public static void MapChatApi(this IEndpointRouteBuilder app)
    {
        var chat = app.MapGroup("/api/chat");
        chat.MapPost("/", Send).RequireRateLimiting(RateLimitPolicy);
        chat.MapGet("/{sessionId}", History);
    }

    public sealed record ChatRequest(string SessionId, string Message, string? Language);
    public sealed record ChatResponse(string Reply, bool NeedsHuman);
    public sealed record ChatMessageDto(string Role, string Text, DateTime At);

    private static async Task<IResult> Send(
        ChatRequest req, IServiceProvider services, IOptions<WsOptions> o, ILogger<Receptionist> log, CancellationToken ct)
    {
        if (!ValidSession(req.SessionId) || string.IsNullOrWhiteSpace(req.Message))
            return Results.ValidationProblem(new Dictionary<string, string[]> { ["message"] = ["Message and session are required."] });

        // No Claude API key configured: the widget shows a "call us" message instead.
        var receptionist = services.GetService<Receptionist>();
        if (receptionist == null) return Results.Problem(statusCode: 503, title: "Chat is not configured", type: "ChatUnavailable");

        try
        {
            var reply = await receptionist.ReplyAsync(o.Value.SalonId, Channel.WebChat, req.SessionId, req.Message, req.Language, ct);
            return Results.Ok(new ChatResponse(reply.Text, reply.NeedsHuman));
        }
        catch (AnthropicApiException ex)
        {
            log.LogError(ex, "Claude API error in web chat");
            return Results.Problem(statusCode: 503, title: "Chat is temporarily unavailable", type: "ChatUnavailable");
        }
    }

    private static async Task<IResult> History(string sessionId, WsDbContext db, IOptions<WsOptions> o, CancellationToken ct)
    {
        if (!ValidSession(sessionId)) return Results.NotFound();
        var messages = await db.ConversationMessages.AsNoTracking()
            .Where(m => db.Conversations.Any(c => c.Id == m.ConversationId && c.SalonId == o.Value.SalonId
                                                  && c.Channel == Channel.WebChat && c.ExternalId == sessionId))
            .Where(m => (m.Role == MessageRole.User || m.Role == MessageRole.Assistant || m.Role == MessageRole.Staff) && m.Text != "")
            .OrderBy(m => m.Id)
            .Select(m => new ChatMessageDto(m.Role == MessageRole.User ? "user" : "assistant", m.Text, m.CreatedAtUtc))
            .ToListAsync(ct);
        return Results.Ok(messages);
    }

    /// <summary>Session ids are random UUIDs generated by the widget; anything else is rejected.</summary>
    private static bool ValidSession(string? id) => Guid.TryParse(id, out _);
}
